puzzles:
   path: /puzzles
   controller: App\Http\Controller\PuzzleController::list
   methods: GET

random_puzzle:
   path: /puzzles/random
   controller: App\Http\Controller\PuzzleController::random
   methods: GET

store_puzzle:
   path: /puzzles/{encoding}
   controller: App\Http\Controller\PuzzleController::store
   methods: POST

get_puzzle:
   path: /puzzles/{encoding}
   controller: App\Http\Controller\PuzzleController::index
   methods: POST

solve_puzzle:
   path: /puzzles/{encoding}/solution
   controller: App\Http\Controller\SolutionController::index
   methods: GET
