puzzles:
   path: /puzzles
   controller: App\Http\Controller\ListPuzzlesController
   methods: GET
   defaults:
        _format: json
#
# random_puzzle:
#    path: /puzzles/random
#    controller: App\Http\Controller\PuzzleController::random
#    methods: GET
#    defaults:
#         _format: json
#
store_puzzle:
   path: /puzzles
   controller: App\Http\Controller\StorePuzzleController
   methods: POST
   defaults:
        _format: json

get_puzzle:
   path: /puzzles/{uuid}
   controller: App\Http\Controller\FetchPuzzleController
   methods: GET
   defaults:
        _format: json

solve_puzzle:
   path: /puzzles/{encoding}/solution
   controller: App\Http\Controller\SolutionController::index
   methods: GET
   defaults:
        _format: json
