puzzles:
   path: /puzzles
   controller: App\Application\Controller\PuzzleController::index
   methods: GET

random_puzzle:
   path: /puzzles/random
   controller: App\Application\Controller\PuzzleController::get
   methods: GET

save_puzzle:
   path: /puzzles/{encoding}
   controller: App\Application\Controller\PuzzleController::store
   methods: POST

solve_puzzle:
   path: /puzzles/{encoding}/solution
   controller: App\Application\Controller\SolutionController::index
   methods: GET
