get_puzzle:
   path: /puzzle
   controller: App\Application\Controller\PuzzleController
   methods: GET

test:
   path: /test
   controller: App\Controller\TestController::index
   methods: GET

home:
   path: /
   controller: App\Controller\TestController::index
   methods: GET
